### ISSUE TITLE
Promise.withResolvers is not a function error in @pdfslick/react v2.20

### ISSUE THREAD

**Issue by Mario8419** [pdfslick/pdfslick#92]
After upgrading @pdfslick/react from v1.5.2 to v2.20, I encountered the following error when trying to render a PDF:

TypeError: Promise.withResolvers is not a function
    at Object.<anonymous> (node_modules/pdfjs-dist/build/pdf.js)

Steps to Reproduce:
Install the latest version of @pdfslick/react (2.20).

Expected Behavior:
The PDF should render correctly without any runtime errors, like in 1.5.2

Actual Behavior:
The app crashes with TypeError: Promise.withResolvers is not a function.

**Comment by van100j** [comment]
@Mario8419 we've updated PDFSlick with pdf.js 4 which uses `withResolvers` available with node >v22 so you might take a look at that. I'd also make sure to load pdf viewer on the client side only.

Please provide more details if you need more help with this (code samples etc.)

**Comment by Mario8419** [comment]
updated to node, 22.14 -> same problem

```
import { usePDFSlick } from "@pdfslick/react"

const [instance, updateInstance] = usePDF({})
  const { viewerRef, usePDFSlickStore, PDFSlickViewer, isDocumentLoaded } = usePDFSlick(
    instance.url,
    {
      singlePageViewer: true,
      scaleValue: "page-fit"
    })
  const scale = usePDFSlickStore((s) => s.scale);
  const numPages = usePDFSlickStore((s) => s.numPages);
  const pageNumber = usePDFSlickStore((s) => s.pageNumber);
  const pdfSlick = usePDFSlickStore((s) => s.pdfSlick);

<div className="pdfSlick">
          <PDFSlickViewer {...{ viewerRef, usePDFSlickStore }} />       
        </div>
```

**Comment by van100j** [comment]
I don't see anything wrong with this, the PDFSlick demos look exactly the same and there arean't any issues. But what I don't see is how you use this component — like I mentioned before make sure [it loads on the client only](https://github.com/pdfslick/pdfslick/blob/main/apps/web/pages/examples/pdf-viewer-app.tsx#L7).

**Comment by RinseV** [comment]
This issue can also happen if you are [using a browser that does not support `Promise.withResolvers`](https://caniuse.com/?search=Promise.withResolvers). pdfjs does ship with [a legacy build](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#which-browsersenvironments-are-supported) that does not use `Promise.withResolvers` and so is usable on older browsers as well.

If you want to fix the issue, you have to patch `@pdfslick/core` to use the legacy build of `pdfjs-dist`. You can do this by changing 2 lines in `@pdfslick/core`. The first one is to update the import from `pdfjs-dist/web/pdf_viewer.mjs` to `pdfjs-dist/legacy/web/pdf_viewer.mjs`. The second one is to update the worker URL from `pdfjs-dist/build/pdf.worker.min.mjs` to `pdfjs-dist/legacy/build/pdf.worker.min.mjs`.

Perhaps a check for compatibility can be included in PDFSlick itself? That way users don't have to patch the dependency themselves if they need to support older browsers. An example of such functionality can be found [here](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/2301#issuecomment-2208463650).

**Comment by RinseV** [comment]
I'm not sure what the best way is to include this change, ideally it's an option in PDFSlick that you can just change, i.e. `useLegacyPdfJsBuild`, but then I'm not sure how to dynamically change the import paths in the code depending on this variable
